### ISSUE TITLE
feature: new deploy engine

### ISSUE THREAD

**Issue by ilya-lesikov** [werf/werf#5639]
## Abstract

We experienced numerous problems with Helm deploys, much of them were very hard to solve. Also, the extensibility of the code that managed deploys in Helm was pretty limited, making implementation of new features too expensive.

We decided to develop a new alternative deploy engine which is 100% backwards compatible with Helm/werf, but with the problems of the previous implementation solved and with extensibility and maintainability improved. New deploy engine will become the default one when stabilized.

New deploy engine can be activated using `WERF_EXPERIMENTAL_DEPLOY_ENGINE=1` since `v1.2.234`, no other changes required.

## Major new features roadmap

- [x] 3-way merge replaced with native Server-Side Apply;
- [x] CRDs from `/crds` now deployed on install and upgrade, not just install;
- [x] CRDs from `/crds` now can be created and updated, not only created;
- [x] resource updates are skipped if corresponding cluster resources already as desired;
- [x] if no changes in the whole release then the release is skipped;
- [x] resources stored in previous release that can't be server-side validated (Kubernetes upgraded, CRD removed, ...) won't brick further upgrades;
- [x] newly created resources won't be deleted on failed release;
- [x] report of what was actually done in the end of deployment;
- [ ] `werf lint`;
- [x] `werf plan/diff`;
- [ ] easier management of immutable resources;
- [x] easier management of resources with `"helm.sh/resource-policy": keep`;
- [ ] Helm as a library

## TODO:
- [x] ci-env with its constantly updating annotations trigger resource updates every time;

**Comment by ilya-lesikov** [comment]
Released in experimental mode in alpha channel.

**Comment by ilya-lesikov** [comment]
Here is a PR, where most of the changes are: https://github.com/werf/3p-helm/pull/254/files

**Comment by shurup** [comment]
The werf's new deployment engine is called **Nelm** now, and further related announcements can be found in this discussion: https://github.com/werf/werf/discussions/5657

There's also a separate repo for Nelm: https://github.com/werf/nelm

**Comment by ilya-lesikov** [comment]
The new deployment engine is generally complete and stabilized, although we plan for a second iteration to improve on it. It can be enabled in werf v1.2 with `export WERF_NELM=1` and it will be the only deployment engine in soon-to-be released v2.0.
